name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: change submodule from git to https
        run: sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules

      - name: Update theme
        # As the theme is added as submodule, pull to init
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          # Check the version here: https://formulae.brew.sh/api/formula/hugo.json
          hugo-version: "0.82.0"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: alvarogarcia7/alvarogarcia7.github.io
          publish_dir: ./public # the default folder that hugo publishes to
          keep_files: true
          user_name: "alvarogarcia7 (via Github Actions)"
          user_email: alvarogarcia7@users.noreply.github.com
          publish_branch: master
